// <auto-generated />
using System;
using Controle_de_Vendas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Controle_de_Vendas.Migrations
{
    [DbContext(typeof(Controle_de_VendasContext))]
    [Migration("20210206220614_OutrasEntidades")]
    partial class OutrasEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Controle_de_Vendas.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("DepartamentoID");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("Controle_de_Vendas.Models.Vendas", b =>
                {
                    b.Property<int>("VendasID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<double>("Qtde");

                    b.Property<int>("Status");

                    b.Property<int?>("VendedorID");

                    b.HasKey("VendasID");

                    b.HasIndex("VendedorID");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("Controle_de_Vendas.Models.Vendedor", b =>
                {
                    b.Property<int>("VendedorID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Aniversario");

                    b.Property<int?>("DepartamentoID");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<double>("SalarioBase");

                    b.HasKey("VendedorID");

                    b.HasIndex("DepartamentoID");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Controle_de_Vendas.Models.Vendas", b =>
                {
                    b.HasOne("Controle_de_Vendas.Models.Vendedor", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorID");
                });

            modelBuilder.Entity("Controle_de_Vendas.Models.Vendedor", b =>
                {
                    b.HasOne("Controle_de_Vendas.Models.Departamento", "Departamento")
                        .WithMany("Vendedores")
                        .HasForeignKey("DepartamentoID");
                });
#pragma warning restore 612, 618
        }
    }
}
